name: Security audit

on:
    push:
      paths:
        - '**/Cargo.toml'
        - '**/Cargo.lock'
    schedule:
      - cron: '0 0 * * *'

jobs:
    audit:
        name: Audit
        uses: edpft/rust-workflows/.github/workflows/audit.yml@main
