name: Test `kafka` binary
on:
  pull_request:
    paths:
      - "kafka/**"

jobs:
  single-node-kafka:
    name: Single node kafka
    uses: ./.github/workflows/test.yml
    with:
      test-name: kafka
      test-args: --node-count 1 --concurrency 2n --time-limit 20 --rate 1000
      binary-name: maelstrom-kafka