on:
  pull_request:
    paths:
      - "broadcast/*"
  workflow_run:
    workflows: ["Continuous integration"]
    types:
      - completed

jobs:
  test:
    name: Test Unique Ids Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          [
            "single_node_broadcast",
            "multi_node_broadcast",
            "fault_tolerant_broadcast",
            "broadcast_efficiency_1",
            "broadcast_efficiency_2",
          ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Maelstrom dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
              openjdk-17-jdk \
              graphviz \
              gnuplot
      - name: Install Maelstrom
        run: |
          wget https://github.com/jepsen-io/maelstrom/releases/download/v0.2.3/maelstrom.tar.bz2
          tar -xf maelstrom.tar.bz2
          rm -rf maelstrom.tar.bz2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        run: |
          cargo test test_${{ matrix.test }}
