on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      test-args:
        required: true
        type: string
      binary-name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Maelstrom dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
              openjdk-17-jdk \
              graphviz \
              gnuplot
      - name: Install Maelstrom
        run: |
          wget https://github.com/jepsen-io/maelstrom/releases/download/v0.2.3/maelstrom.tar.bz2
          tar -xf maelstrom.tar.bz2
          rm -rf maelstrom.tar.bz2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: |
          cargo build -p ${{ inputs.binary-name }} --release
      - name: Run maelstrom test
        run: |
          maelstrom/maelstrom test -w ${{ inputs.test-name }} --bin target/release/${{ inputs.binary-name }} ${{ inputs.test-args }}
